import socket,os
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)  
# Errors are not logged (run with /K to check them)
sock.bind(('127.0.0.1', 8888))  
sock.listen(1)
connection,address = sock.accept()  
buf = connection.recv(1024)  
assert(buf == b'PING\n')
connection.send(b'PONG')
buf = connection.recv(1024)  
assert(buf == b'OK\n')
connection.send(b'Non-ASCII stuff:\x04\x08:\n')
connection.send(b'QUIT')
buf = connection.recv(1024)
assert(buf == b'YEAH\n')
connection.send(b'ABC\xff\x00\x01\x02\x03\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0fCOUCOU')
connection.close()
